routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::permanentRedirect('/', '/dashboard')->name('welcome');

Route::middleware('auth', 'verified')->group(function () {
	Route::view('dashboard', 'dashboard')->name('dashboard');
	Route::view('profile', 'profile')->name('profile');

	// module pelanggan
	Route::get('/pelanggan', 'App\Http\Controllers\MemberController@getPelanggan')->name('getPelanggan');
	Route::get('/pelanggan/update/{id}', 'App\Http\Controllers\MemberController@updatePelanggan')->name('updatePelanggan');
	Route::post('/pelanggan/update/{id}', 'App\Http\Controllers\MemberController@updatePelangganAction')->name('updatePelangganAction');
	Route::get('/pelanggan/create/', 'App\Http\Controllers\MemberController@createPelanggan')->name('createPelanggan');
	Route::post('/pelanggan/create/', 'App\Http\Controllers\MemberController@createPelangganAction')->name('createPelangganAction');
	Route::delete('/pelanggan/delete/{id}', 'App\Http\Controllers\MemberController@deletePelanggan')->name('deletePelanggan');

	// module outlet
	Route::get('/outlet', 'App\Http\Controllers\OutletController@getOutlet')->name('getOutlet');
	Route::get('/outlet/update/{id}', 'App\Http\Controllers\OutletController@updateOutlet')->name('updateOutlet');
	Route::post('/outlet/update/{id}', 'App\Http\Controllers\OutletController@updateOutletAction')->name('updateOutletAction');
	Route::get('/outlet/create/', 'App\Http\Controllers\OutletController@createOutlet')->name('createOutlet');
	Route::post('/outlet/create/', 'App\Http\Controllers\OutletController@createOutletAction')->name('createOutletAction');
	Route::delete('/outlet/delete/{id}', 'App\Http\Controllers\OutletController@deleteOutlet')->name('deleteOutlet');
	
	// module paket
	Route::get('/paket', 'App\Http\Controllers\PaketController@getPaket')->name('getPaket');
	Route::get('/paket/update/{id}', 'App\Http\Controllers\PaketController@updatePaket')->name('updatePaket');
	Route::post('/paket/update/{id}', 'App\Http\Controllers\PaketController@updatePaketAction')->name('updatePaketAction');
	Route::get('/paket/create/', 'App\Http\Controllers\PaketController@createPaket')->name('createPaket');
	Route::post('/paket/create/', 'App\Http\Controllers\PaketController@createPaketAction')->name('createPaketAction');
	Route::delete('/paket/delete/{id}', 'App\Http\Controllers\PaketController@deletePaket')->name('deletePaket');

	
	// module pengguna
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'avatar'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getAvatarUrlAttribute()
    {
        if ($this->avatar != null) :
            return asset($this->avatar);
        else :
            return 'https://ui-avatars.com/api/?name=' . str_replace(' ', '+', $this->name) . '&background=fff&color=6777ef&size=100';
        endif;
    }
}

resources/views/dashboard.blade.php
@extends('layouts.backend')

@section('title', 'Dashboard')

@section('content')
<div class="card">
    <div class="card-header">
        <h4>Dashboard</h4>
    </div>
    <div class="card-body">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo ducimus temporibus aut ratione maxime
        accusamus
        commodi esse itaque tenetur. Temporibus ducimus ea veniam quisquam rerum vitae? Animi quos laudantium quam?
    </div>
</div>
@endsection

resources/views/profile.blade.php
@extends('layouts.backend')

@section('title', 'Profile')

@section('content')
<x-section-header heading="Profile" breadcrumb="profile" />
<x-section-sub-header title="Hi! {{ Str::words(auth()->user()->name, 1, '') }}"
  lead="Change information about yourself on this page." />

<div class="row mt-sm-4">
  {{-- <div class="col-12 col-md-12 col-lg-5">
    <div class="card profile-widget">
      <div class="profile-widget-header">
        <img alt="image" src="{{ auth()->user()->avatar_url }}" class="rounded-circle profile-widget-picture">
        <div class="profile-widget-items">
          <div class="profile-widget-item">
            <div class="profile-widget-item-label">Posts</div>
            <div class="profile-widget-item-value">187</div>
          </div>
          <div class="profile-widget-item">
            <div class="profile-widget-item-label">Followers</div>
            <div class="profile-widget-item-value">6,8K</div>
          </div>
          <div class="profile-widget-item">
            <div class="profile-widget-item-label">Following</div>
            <div class="profile-widget-item-value">2,1K</div>
          </div>
        </div>
      </div>
      <div class="profile-widget-description">
        <div class="profile-widget-name">Ujang Maman <div class="text-muted d-inline font-weight-normal">
            <div class="slash"></div> Web Developer
          </div>
        </div>
        Ujang maman is a superhero name in <b>Indonesia</b>, especially in my family. He is not a fictional character
        but an original hero in my family, a hero for his children and for his wife. So, I use the name as a user in
        this template. Not a tribute, I'm just bored with <b>'John Doe'</b>.
      </div>
      <div class="card-footer text-center">
        <div class="font-weight-bold mb-2">Follow Ujang On</div>
        <a href="#" class="btn btn-social-icon btn-facebook mr-1">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="#" class="btn btn-social-icon btn-twitter mr-1">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="#" class="btn btn-social-icon btn-github mr-1">
          <i class="fab fa-github"></i>
        </a>
        <a href="#" class="btn btn-social-icon btn-instagram">
          <i class="fab fa-instagram"></i>
        </a>
      </div>
    </div>
    @if (Laravel\Fortify\Features::enabled(Laravel\Fortify\Features::twoFactorAuthentication()))
    @include('profile.two-factor-authentication-form')
    @endif
  </div> --}}
  <div class="col-12 col-md-6 col-lg-6">
    @if (session('status'))
    <div class="alert alert-primary alert-dismissible show fade">
      <div class="alert-body">
        <button class="close" data-dismiss="alert">
          <span>&times;</span>
        </button>
        @if (session('status')=='profile-information-updated')
        Profile has been updated.
        @endif
        @if (session('status')=='password-updated')
        Password has been updated.
        @endif
        @if (session('status')=='two-factor-authentication-disabled')
        Two factor authentication disabled.
        @endif
        @if (session('status')=='two-factor-authentication-enabled')
        Two factor authentication enabled.
        @endif
        @if (session('status')=='recovery-codes-generated')
        Recovery codes generated.
        @endif
      </div>
    </div>
    @endif

    @if (Laravel\Fortify\Features::enabled(Laravel\Fortify\Features::updateProfileInformation()))
    @include('profile.update-profile-information-form')
    @endif

    @if (Laravel\Fortify\Features::enabled(Laravel\Fortify\Features::updatePasswords()))
    @include('profile.update-password-form')
    @endif
  </div>
</div>
@endsection